---
upgrade_providers:
  - |
    The ``configuration`` method of :class:`.BasicSimulator` has been removed following its deprecation  
    in Qiskit 1.3. This method returned a ``BackendConfiguration`` instance,  
    a class that was part of the discontinued ``BackendV1`` workflow and is also removed in Qiskit 2.0.
    The individual configuration elements can now be retrieved directly from the backend or from the contained  
    :class:`.Target` instance (``backend.target``).  

    The ``run_experiment`` method of :class:`.BasicSimulator` has also been removed.  
    This method took an instance of the ``QasmQobjExperiment`` class as an input argument,  
    a class that has been deprecated since Qiskit 1.2 and was removed with the ``Qobj`` workflow Qiskit 2.0.  
